import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import { ambiente } from './configuracao/ambiente.js';
import { pastaUploads } from './configuracao/upload.js';
import rotas from './rotas/index.js';
import { rotaNaoEncontrada, tratarErros } from './intermediarios/tratamentoErros.js';

export const app = express();
app.disable('x-powered-by');
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: ambiente.frontendUrl, credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true, limit: '1mb' }));
app.use(cookieParser());
app.use('/uploads', express.static(pastaUploads, { maxAge: ambiente.nodeEnv === 'production' ? '1d' : 0 }));
app.use('/api', rotas);
app.use(rotaNaoEncontrada);
app.use(tratarErros);
