import { useEffect, useState } from 'react';
import { api, urlMidia } from '../servicos/api.js';
import { useAutenticacao } from '../contextos/ContextoAutenticacao.jsx';
import { CampoSenha } from '../componentes/CampoSenha.jsx';
import { Avatar } from '../componentes/Avatar.jsx';

export function MeuPerfil() {
  const { usuario, recarregarUsuario } = useAutenticacao();
  const [form, setForm] = useState({ nome: usuario.nome, email: usuario.email, telefone: usuario.telefone || '' });
  const [senha, setSenha] = useState({ senhaAtual: '', novaSenha: '', confirmar: '' });
  const [mensagem, setMensagem] = useState(''); const [erro, setErro] = useState(''); const [enviandoFoto, setEnviandoFoto] = useState(false);
  useEffect(() => setForm({ nome: usuario.nome, email: usuario.email, telefone: usuario.telefone || '' }), [usuario]);

  async function salvar(e) { e.preventDefault(); setErro(''); setMensagem(''); try { await api('/usuarios/meu-perfil', { method: 'PUT', body: JSON.stringify(form) }); await recarregarUsuario(); setMensagem('Dados pessoais atualizados.'); } catch (x) { setErro(x.message); } }
  async function alterarSenha(e) { e.preventDefault(); setErro(''); setMensagem(''); if (senha.novaSenha !== senha.confirmar) return setErro('A confirmacao da nova senha nao confere.'); try { await api('/usuarios/minha-senha', { method: 'PATCH', body: JSON.stringify({ senhaAtual: senha.senhaAtual, novaSenha: senha.novaSenha }) }); setSenha({ senhaAtual: '', novaSenha: '', confirmar: '' }); setMensagem('Senha alterada com sucesso.'); } catch (x) { setErro(x.message); } }
  async function enviarFoto(e) { const arquivo = e.target.files?.[0]; if (!arquivo) return; setEnviandoFoto(true); setErro(''); const dados = new FormData(); dados.append('foto', arquivo); try { await api('/usuarios/minha-foto', { method: 'POST', body: dados }); await recarregarUsuario(); setMensagem('Foto de perfil atualizada.'); } catch (x) { setErro(x.message); } finally { setEnviandoFoto(false); e.target.value=''; } }
  async function removerFoto() { try { await api('/usuarios/minha-foto', { method: 'DELETE' }); await recarregarUsuario(); setMensagem('Foto removida.'); } catch (x) { setErro(x.message); } }

  return <div><div className="titulo-secao"><span className="rotulo">Conta</span><h1>Meu perfil</h1><p className="texto-suave">Gerencie seus dados, foto e seguranca da conta.</p></div>{mensagem && <div className="alerta sucesso">{mensagem}</div>}{erro && <div className="alerta erro">{erro}</div>}<section className="formulario-cartao"><h2>Foto de perfil</h2><div className="upload-perfil"><Avatar nome={usuario.nome} fotoUrl={usuario.fotoUrl} tamanho="extra" /><div><label className="botao-secundario arquivo-botao">{enviandoFoto ? 'Enviando...' : 'Escolher imagem'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={enviarFoto} disabled={enviandoFoto} /></label><p className="ajuda-campo">JPG, PNG ou WEBP. Maximo 5 MB.</p>{usuario.fotoUrl && <button className="link-perigo" onClick={removerFoto}>Remover foto</button>}</div></div></section><section className="formulario-cartao secao-interna"><h2>Dados pessoais</h2><form className="formulario" onSubmit={salvar}><div className="grade-dois"><label>Nome<input required minLength="3" value={form.nome} onChange={(e) => setForm({ ...form, nome: e.target.value })} /></label><label>E-mail<input type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label></div><label>Telefone<input maxLength="30" value={form.telefone} onChange={(e) => setForm({ ...form, telefone: e.target.value })} placeholder="(51) 99999-9999" /></label><button className="botao largura-botao">Salvar dados</button></form></section><section className="formulario-cartao secao-interna"><h2>Alterar senha</h2><form className="formulario largura-media" onSubmit={alterarSenha}><CampoSenha id="senha-atual" rotulo="Senha atual" valor={senha.senhaAtual} aoAlterar={(e) => setSenha({ ...senha, senhaAtual: e.target.value })} /><CampoSenha id="nova-senha" rotulo="Nova senha" valor={senha.novaSenha} aoAlterar={(e) => setSenha({ ...senha, novaSenha: e.target.value })} tamanhoMinimo={8} autoComplete="new-password" /><p className="ajuda-campo">Use 8 ou mais caracteres com letra maiuscula, minuscula e numero.</p><CampoSenha id="confirmar-nova" rotulo="Confirmar nova senha" valor={senha.confirmar} aoAlterar={(e) => setSenha({ ...senha, confirmar: e.target.value })} tamanhoMinimo={8} autoComplete="new-password" /><button className="botao largura-botao">Alterar senha</button></form></section></div>;
}
