import { useEffect, useState } from 'react';
import { api } from '../servicos/api.js';

const vazio = { categoriaId: '', titulo: '', descricao: '', precoBase: '' };
export function MeusServicos() {
  const [servicos, setServicos] = useState([]); const [categorias, setCategorias] = useState([]); const [form, setForm] = useState(vazio); const [editando, setEditando] = useState(null); const [erro, setErro] = useState(''); const [mensagem, setMensagem] = useState('');
  async function carregar() { const [s,c] = await Promise.all([api('/servicos/meus'), api('/categorias')]); setServicos(s.servicos); setCategorias(c.categorias); }
  useEffect(() => { carregar().catch((e) => setErro(e.message)); }, []);
  async function salvar(e) { e.preventDefault(); setErro(''); try { const dados = { ...form, precoBase: form.precoBase || null }; if (editando) await api(`/servicos/${editando}`, { method: 'PUT', body: JSON.stringify(dados) }); else await api('/servicos', { method: 'POST', body: JSON.stringify(dados) }); setForm(vazio); setEditando(null); setMensagem(editando ? 'Servico atualizado.' : 'Servico cadastrado.'); await carregar(); } catch (x) { setErro(x.message); } }
  function editar(s) { setEditando(s.id); setForm({ categoriaId: s.categoriaId, titulo: s.titulo, descricao: s.descricao || '', precoBase: s.precoBase || '' }); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async function alternar(s) { try { await api(`/servicos/${s.id}`, { method: 'PUT', body: JSON.stringify({ ativo: !s.ativo }) }); await carregar(); } catch (x) { setErro(x.message); } }
  async function remover(s) { if (!confirm(`Remover o servico "${s.titulo}"?`)) return; try { await api(`/servicos/${s.id}`, { method: 'DELETE' }); await carregar(); } catch (x) { setErro(x.message); } }
  return <div><div className="titulo-secao"><span className="rotulo">Prestador</span><h1>Meus servicos</h1><p className="texto-suave">Cadastre e organize o que voce oferece.</p></div>{mensagem && <div className="alerta sucesso">{mensagem}</div>}{erro && <div className="alerta erro">{erro}</div>}<section className="formulario-cartao"><h2>{editando ? 'Editar servico' : 'Novo servico'}</h2><form className="formulario" onSubmit={salvar}><div className="grade-dois"><label>Categoria<select required value={form.categoriaId} onChange={(e) => setForm({ ...form, categoriaId: e.target.value })}><option value="">Selecione</option>{categorias.map((c) => <option key={c.id} value={c.id}>{c.nome}</option>)}</select></label><label>Titulo<input required minLength="3" value={form.titulo} onChange={(e) => setForm({ ...form, titulo: e.target.value })} /></label></div><label>Descricao<textarea rows="4" maxLength="2000" value={form.descricao} onChange={(e) => setForm({ ...form, descricao: e.target.value })} /></label><label>Preco base<input type="number" min="0" step="0.01" value={form.precoBase} onChange={(e) => setForm({ ...form, precoBase: e.target.value })} placeholder="Deixe vazio para valor sob consulta" /></label><div className="acoes"><button className="botao">{editando ? 'Salvar alteracoes' : 'Cadastrar servico'}</button>{editando && <button type="button" className="botao-secundario" onClick={() => { setEditando(null); setForm(vazio); }}>Cancelar</button>}</div></form></section><section className="secao-interna"><h2>Servicos cadastrados</h2><div className="lista-simples">{servicos.map((s) => <article key={s.id} className="linha-gerencial"><div><div className="tags"><span className="tag">{s.categoria?.nome}</span><span className={`status ${s.ativo ? 'status-aceito' : 'status-cancelado'}`}>{s.ativo ? 'ativo' : 'inativo'}</span></div><h3>{s.titulo}</h3><p className="texto-suave">{s.descricao || 'Sem descricao.'}</p><strong>{s.precoBase ? `R$ ${Number(s.precoBase).toFixed(2).replace('.', ',')}` : 'Valor sob consulta'}</strong></div><div className="acoes"><button className="botao-secundario botao-pequeno" onClick={() => editar(s)}>Editar</button><button className="botao-secundario botao-pequeno" onClick={() => alternar(s)}>{s.ativo ? 'Desativar' : 'Ativar'}</button><button className="link-perigo" onClick={() => remover(s)}>Remover</button></div></article>)}{!servicos.length && <div className="vazio">Nenhum servico cadastrado.</div>}</div></section></div>;
}
