import { useEffect, useState } from 'react';
import { api } from '../servicos/api.js';
import { useAutenticacao } from '../contextos/ContextoAutenticacao.jsx';
import { useNotificacoes } from '../contextos/ContextoNotificacoes.jsx';

function fmt(v) { return new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(v)); }
function paraLocalInput(v) { const d = new Date(v); d.setMinutes(d.getMinutes() - d.getTimezoneOffset()); return d.toISOString().slice(0,16); }

export function MinhaAgenda() {
  const { usuario } = useAutenticacao(); const { recarregar: recarregarNotificacoes } = useNotificacoes();
  const [agendamentos, setAgendamentos] = useState([]); const [disponibilidades, setDisponibilidades] = useState([]); const [nova, setNova] = useState({ inicio:'', fim:'', observacao:'' }); const [ajustando, setAjustando] = useState(null); const [erro, setErro] = useState(''); const [mensagem, setMensagem] = useState('');
  async function carregar() { const a = await api('/agendamentos'); setAgendamentos(a.agendamentos); if (usuario.tipo === 'prestador') { const d = await api('/disponibilidades/minhas'); setDisponibilidades(d.disponibilidades); } }
  useEffect(() => { carregar().catch((e) => setErro(e.message)); }, [usuario.tipo]);
  async function criarDisponibilidade(e) { e.preventDefault(); try { await api('/disponibilidades', { method:'POST', body:JSON.stringify({ ...nova, inicio:new Date(nova.inicio).toISOString(), fim:new Date(nova.fim).toISOString() }) }); setNova({ inicio:'', fim:'', observacao:'' }); setMensagem('Disponibilidade cadastrada.'); await carregar(); } catch(x){setErro(x.message);} }
  async function removerDisp(id){ if(!confirm('Remover este periodo de disponibilidade?')) return; try{await api(`/disponibilidades/${id}`,{method:'DELETE'});await carregar();}catch(x){setErro(x.message);} }
  async function status(id, st){try{await api(`/agendamentos/${id}/status`,{method:'PATCH',body:JSON.stringify({status:st})});await carregar();await recarregarNotificacoes();}catch(x){setErro(x.message);} }
  async function concluir(id){try{await api(`/agendamentos/${id}/concluir`,{method:'PATCH'});await carregar();await recarregarNotificacoes();setMensagem('Atendimento marcado como concluido.');}catch(x){setErro(x.message);} }
  async function salvarHorario(e){e.preventDefault();try{await api(`/agendamentos/${ajustando.id}/horario`,{method:'PATCH',body:JSON.stringify({inicio:new Date(ajustando.inicio).toISOString(),fim:new Date(ajustando.fim).toISOString()})});setAjustando(null);await carregar();setMensagem('Horario ajustado. O cliente foi notificado.');}catch(x){setErro(x.message);} }
  const futuros = [...agendamentos].sort((a,b)=>new Date(a.inicio)-new Date(b.inicio));
  return <div><div className="titulo-secao"><span className="rotulo">Agenda</span><h1>{usuario.tipo === 'prestador' ? 'Agenda e solicitacoes' : 'Meus agendamentos'}</h1><p className="texto-suave">Acompanhe horarios, status e atendimentos.</p></div>{mensagem&&<div className="alerta sucesso">{mensagem}</div>}{erro&&<div className="alerta erro">{erro}</div>}{usuario.tipo==='prestador'&&<section className="formulario-cartao"><h2>Cadastrar disponibilidade</h2><form className="formulario" onSubmit={criarDisponibilidade}><div className="grade-dois"><label>Inicio<input type="datetime-local" required value={nova.inicio} onChange={(e)=>setNova({...nova,inicio:e.target.value})}/></label><label>Fim<input type="datetime-local" required value={nova.fim} onChange={(e)=>setNova({...nova,fim:e.target.value})}/></label></div><label>Observacao<input maxLength="255" value={nova.observacao} onChange={(e)=>setNova({...nova,observacao:e.target.value})} placeholder="Ex.: atendimento somente em Torres"/></label><button className="botao largura-botao">Adicionar periodo</button></form><div className="chips-disponibilidade">{disponibilidades.map((d)=><div key={d.id}><span>{fmt(d.inicio)} ate {fmt(d.fim)}</span><button onClick={()=>removerDisp(d.id)}>×</button></div>)}{!disponibilidades.length&&<span className="texto-suave">Nenhum periodo futuro cadastrado.</span>}</div></section>}
  <section className="secao-interna"><h2>Agendamentos</h2><div className="lista-simples">{futuros.map((a)=><article key={a.id} className="linha-agendamento"><div><div className="tags"><span className={`status status-${a.status}`}>{a.status}</span>{a.concluidoEm&&<span className="status status-concluido">concluido</span>}</div><h3>{a.servico?.titulo || 'Servico nao especificado'}</h3><p><strong>{fmt(a.inicio)}</strong> ate {fmt(a.fim)}</p><p>{usuario.tipo==='prestador'?`Cliente: ${a.cliente?.nome}`:`Prestador: ${a.prestador?.nome}`}</p>{a.descricao&&<p className="texto-suave">{a.descricao}</p>}{a.avaliacao&&<span className="texto-suave">Avaliado com {a.avaliacao.nota} estrela(s)</span>}</div><div className="acoes-coluna">{usuario.tipo==='prestador'&&a.status==='pendente'&&!a.concluidoEm&&<><button className="botao botao-pequeno" onClick={()=>status(a.id,'aceito')}>Aceitar</button><button className="botao-secundario botao-pequeno" onClick={()=>status(a.id,'recusado')}>Recusar</button></>}{usuario.tipo==='prestador'&&['pendente','aceito'].includes(a.status)&&!a.concluidoEm&&<button className="botao-secundario botao-pequeno" onClick={()=>setAjustando({id:a.id,inicio:paraLocalInput(a.inicio),fim:paraLocalInput(a.fim)})}>Ajustar horario</button>}{usuario.tipo==='prestador'&&a.status==='aceito'&&!a.concluidoEm&&<button className="botao-secundario botao-pequeno" onClick={()=>concluir(a.id)}>Concluir atendimento</button>}{usuario.tipo==='cliente'&&['pendente','aceito'].includes(a.status)&&!a.concluidoEm&&<button className="botao-secundario botao-pequeno" onClick={()=>status(a.id,'cancelado')}>Cancelar</button>}</div></article>)}{!agendamentos.length&&<div className="vazio">Nenhum agendamento por enquanto.</div>}</div></section>{ajustando&&<section className="modal-inline"><div className="formulario-cartao"><div className="titulo-linha"><h2>Ajustar horario</h2><button className="botao-icone" onClick={()=>setAjustando(null)}>×</button></div><form className="formulario" onSubmit={salvarHorario}><div className="grade-dois"><label>Novo inicio<input type="datetime-local" required value={ajustando.inicio} onChange={(e)=>setAjustando({...ajustando,inicio:e.target.value})}/></label><label>Novo fim<input type="datetime-local" required value={ajustando.fim} onChange={(e)=>setAjustando({...ajustando,fim:e.target.value})}/></label></div><div className="acoes"><button className="botao">Salvar horario</button><button type="button" className="botao-secundario" onClick={()=>setAjustando(null)}>Cancelar</button></div></form></div></section>}</div>;
}
